### PR TITLE
Following Issue #2

### PR DESCRIPTION
**Pull request by CPerezz**
Added helpers.js file for testing modules and assertRevert testing function from Zeppelin.

### CODE REVIEW

**Comment by tyleryasaka** [comment]
@CPerezz can we import the helper from openzeppelin instead of copying it?

**Comment by CPerezz** [comment]
@tyleryasaka Yes, for sure! I've noticed that asserRevert was replaced for shouldFail. So I've updated it on the tests.

**Comment by tyleryasaka** [comment]
@CPerezz can we remove that helpers directory entirely, and all the files in it? right now this is adding a bunch of files.

**Comment by tyleryasaka** [comment]
what I mean is, we should be importing openzeppelin-solidity as a dependency in package.json, not copying over the files.

**Comment by CPerezz** [comment]
@tyleryasaka My bad, I didn't understand you. I'm on it. Excuse me.

**Comment by tyleryasaka** [comment]
@CPerezz no problem, thank you for fixing this! I wasn't aware of these test helpers - makes life easier and the code cleaner.

**Pull request merged**
