### PR TITLE
add override at code to solve compile error

### PR DESCRIPTION
**Pull request by codev911**

### CODE REVIEW

**Comment by YamenMerhi** [comment]
Hey @codev911 Thanks for the PR!
The error you are encountering are because of the compiler version you are using. Since solidity version `0.8.8` a contract inheriting a function defined in a single inherited interface won't need the `override` keyword. It's the case for `execute` and `setData`. Check [here](https://github.com/ethereum/solidity/releases/tag/v0.8.8) first point.
   
I suggest you use a compiler version starting or higher than `0.8.8` so the code can compile successfully.
We might want to switch our pragma to start from `0.8.8` but that's an internal discussion we will have soon.

**Comment by codev911** [comment]
@YamenMerhi i have try at latest compiler 0.8.17 at remix and got the error of override, and test it at hardhat

**Comment by YamenMerhi** [comment]
@codev911 Can you try to clone the repo and try to compile it?

**Comment by CJ42** [comment]
@codev911 thanks for pointing this out. That's a good thing to have flagged. 
I will merge your PR so that the contracts can be compiled with solc version older than 0.8.8.

Regarding this

> @YamenMerhi i have try at latest compiler 0.8.17 at remix and got the error of override, and test it at hardhat

I have tried compiling with 0.8.17 earlier and it compiled successfully on my side.

**Review by CJ42 — APPROVED** [review]

**Pull request merged**
