### PR TITLE
Added LydianID use-case

### PR DESCRIPTION
**Pull request by conejoninja**

### CODE REVIEW

**Comment by conejoninja** [comment]
We do not have a link to a demo site yet, but are working on one. I will update the PR as soon as it's ready. thanks.

**Comment by franckc** [comment]
Great ! Thank you :)

**Comment by conejoninja** [comment]
Replaced link with one to the demo dapp of LydianID

**Comment by franckc** [comment]
@tyleryasaka Would you be ok merging this PR ? Thanks :)

**Comment by franckc** [comment]
@nick gave me the power to merge in this repo. thank you sir ! going to merge this PR....

**Pull request merged**
